namespace Domain.Enums;

/// <summary>
/// Represents the types of actions that can be audited in the system
/// </summary>
public enum AuditActionType
{
    /// <summary>
    /// Creation of a new entity
    /// </summary>
    Create = 1,
    
    /// <summary>
    /// Update of an existing entity
    /// </summary>
    Update = 2,
    
    /// <summary>
    /// Deletion of an existing entity
    /// </summary>
    Delete = 3,
    
    /// <summary>
    /// User authentication successful
    /// </summary>
    Login = 4,
    
    /// <summary>
    /// User authentication failed
    /// </summary>
    LoginFailed = 5,
    
    /// <summary>
    /// User logged out
    /// </summary>
    Logout = 6,
    
    /// <summary>
    /// User password changed
    /// </summary>
    PasswordChange = 7,
    
    /// <summary>
    /// User password reset request
    /// </summary>
    PasswordReset = 8,
    
    /// <summary>
    /// Book checked out to a member
    /// </summary>
    BookCheckout = 9,
    
    /// <summary>
    /// Book returned by a member
    /// </summary>
    BookReturn = 10,
    
    /// <summary>
    /// Fine created for a member
    /// </summary>
    FineCreated = 11,
    
    /// <summary>
    /// Fine paid by a member
    /// </summary>
    FinePaid = 12,
    
    /// <summary>
    /// Fine waived for a member
    /// </summary>
    FineWaived = 13,
    
    /// <summary>
    /// Book reservation created
    /// </summary>
    ReservationCreated = 14,
    
    /// <summary>
    /// Book reservation fulfilled
    /// </summary>
    ReservationFulfilled = 15,
    
    /// <summary>
    /// Book reservation cancelled
    /// </summary>
    ReservationCancelled = 16,
    
    /// <summary>
    /// User accessed sensitive information
    /// </summary>
    AccessSensitiveData = 17,
    
    /// <summary>
    /// Permission changes for a user
    /// </summary>
    PermissionChange = 18,
    
    /// <summary>
    /// System configuration changes
    /// </summary>
    ConfigurationChange = 19,
    
    /// <summary>
    /// Report generated by a user
    /// </summary>
    ReportGenerated = 20,
    
    /// <summary>
    /// Other actions not categorized above
    /// </summary>
    Other = 99
}